### ISSUE TITLE
Error while running infer.py

### ISSUE THREAD

**Issue by gargisri68** [fukun07/neural-image-captioning#5]
I have successfully trained the model using train.py and while running infer.py, I am getting the following error
`Traceback (most recent call last):
  File "infer.py", line 65, in <module>
    scores = validate(bs, valid_set)
  File "infer.py", line 20, in validate
    sent = beam_searcher.generate(data[1:])
  File "/home/cse/phd/16071009/nic/neural-image-captioning-master/codes/beam_search.py", line 43, in generate
    new_nodes.extend(self._get_new_nodes(n))
  File "/home/cse/phd/16071009/nic/neural-image-captioning-master/codes/beam_search.py", line 69, in _get_new_nodes
    new_s, p = m.step_func(s, w)
  File "/home/cse/phd/16071009/nic/neural-image-captioning-master/codes/model/ss.py", line 104, in step_func
    return self._step_func(state_value, w_value)
  File "/home/cse/phd/16071009/anaconda3/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/cse/phd/16071009/anaconda3/envs/theano/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/cse/phd/16071009/anaconda3/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: Shape mismatch: x has 1064 cols (and 1 rows) but y has 1104 rows (and 2048 cols)
Apply node that caused the error: Dot22(Join.0, ss@lstm#w)
Toposort index: 7
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(1, 1064), (1104, 2048)]
Inputs strides: [(4256, 4), (8192, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Add}[(0, 0)](Dot22.0, InplaceDimShuffle{x,0}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.`

**Comment by fukun07** [comment]
The dimensions of input data and LSTM mismatch. Are you training with mscoco but inference on flickr8k?  Please check [infer.py: line 40](https://github.com/fukun07/neural-image-captioning/blob/master/codes/infer.py#L40).

Scene vector in flickr8k has dimension=40, while in mscoco/flickr30k it has dimension=80. This can lead to dimension incompatibility.

**Comment by gargisri68** [comment]
Thanks, it worked.
